### ISSUE TITLE
Crash on v4.4.1: Call to undefined function get_syndication_links_data()

### ISSUE THREAD

**Issue by snarfed** [dshanske/syndication-links#168]
I saw this crash a few times just now on v4.4.1 (WordPress 6.1.1) while creating a new post, and then updating it, with _Syndicate to Bridgy Fed_ checked:

```
stderr: PHP Fatal error:  Uncaught Error: Call to undefined function get_syndication_links_data() in /usr/home/ryancb/public_html/w/wp-content/plugins/syndication-links/includes/webmentions/class-synprovider-webmention.php:59
stderr: Stack trace:
stderr: #0 /usr/home/ryancb/public_html/w/wp-content/plugins/syndication-links/includes/class-post-syndication.php(127): SynProvider_Webmention->posse(48689)
stderr: #1 /usr/home/ryancb/public_html/w/wp-content/plugins/syndication-links/includes/class-post-syndication.php(286): Post_Syndication::syndication(48689, Array)
stderr: #2 /usr/home/ryancb/public_html/w/wp-includes/class-wp-hook.php(310): Post_Syndication::save_post(48689, Object(WP_Post))
stderr: #3 /usr/home/ryancb/public_html/w/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
stderr: #4 /usr/home/ryancb/public_html/w/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
stderr: #5 /usr/home/ryancb/public_html/w/wp-includes/post.php(4706): do_action('save_post_post', 48689, Object(WP_Post), true)
stderr: #6 /usr/home/ryancb/public_html/w/wp-includes/post.php(4819): wp_inse in /usr/home/ryancb/public_html/w/wp-content/plugins/syndication-links/includes/webmentions/class-synprovider-webmention.php on line 59
```

**Comment by dshanske** [comment]
Resolved via https://github.com/dshanske/syndication-links/commit/66c72bde66fc3eca5a5e6fc8d1e515b5f7ee1203
