### ISSUE TITLE
Bridgy Fed crash

### ISSUE THREAD

**Issue by snarfed** [dshanske/syndication-links#172]
Hi again! Bridgy Fed is still crashing, even with 4.4.2 and the fix for #168. New crash this time at least!

```
WordPress version 6.1.1
Active theme: snarfed-ryu (version )
Current plugin: Syndication Links (version 4.4.2)
PHP version 7.4.33

Error Details
=============
An error of type E_ERROR was caused in line 23 of the file /usr/home/ryancb/public_html/w/wp-content/plugins/syndication-links/includes/webmentions/class-synprovider-webmention.php. Error message: Uncaught Error: Cannot use object of type WP_Error as array in /usr/home/ryancb/public_html/w/wp-content/plugins/syndication-links/includes/webmentions/class-synprovider-webmention.php:23
Stack trace:
#0 /usr/home/ryancb/public_html/w/wp-content/plugins/syndication-links/includes/webmentions/class-synprovider-webmention.php(57): SynProvider_Webmention->send_webmention('https://snarfed./..')
#1 /usr/home/ryancb/public_html/w/wp-content/plugins/syndication-links/includes/class-post-syndication.php(127): SynProvider_Webmention->posse(48725)
#2 /usr/home/ryancb/public_html/w/wp-content/plugins/syndication-links/includes/class-post-syndication.php(286): Post_Syndication::syndication(48725, Array)
#3 /usr/home/ryancb/public_html/w/wp-includes/class-wp-hook.php(310): Post_Syndication::save_post(48725, Object(WP_Post))
#4 /usr/home/ryancb/public_html/w/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /usr/home/ryancb/public_html/w/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
```

Got this from

**Comment by dshanske** [comment]
This should be fixed as of the latest push.
